
load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")

git_repository(
    name = "gtest",
    remote = "https://github.com/google/googletest.git",
    branch = "master",
    commit = "f7c178ecb33c92763fa41d4999db30aaf43a6b30",
)

git_repository(
    name = "com_google_absl",
    remote = "https://github.com/abseil/abseil-cpp.git",
    branch = "master",
    commit = "8f11724067248acc330b4d1f12f0c76d03f2cfb1",
)

#local_repository(
#    name = "com_google_absl",
#    path = "C:\\Users\\guo\\Desktop\\compile_windows\\abseil-cpp",
#    path = "/home/guo/Github/abseil-cpp",
#)

